version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-app
    container_name: my-app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: ["python", "src/main.py"]